
-- Add new dynamic settings columns
ALTER TABLE public.commission_settings
  ADD COLUMN IF NOT EXISTS prediction_min_bet numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS prediction_max_bet numeric NOT NULL DEFAULT 10000,
  ADD COLUMN IF NOT EXISTS deposit_min_amount numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS deposit_max_amount numeric NOT NULL DEFAULT 50000,
  ADD COLUMN IF NOT EXISTS push_prompt_cooldown_days integer NOT NULL DEFAULT 14,
  ADD COLUMN IF NOT EXISTS deposit_expiry_minutes integer NOT NULL DEFAULT 60;

-- Recreate the public view to expose the new columns
CREATE OR REPLACE VIEW public.public_commission_settings AS
SELECT
  prediction_fee_percent,
  creator_fee_percent,
  creator_fee_blue_percent,
  creator_fee_gold_percent,
  referrer_commission_percent,
  exit_fee_percent,
  quick_trade_fee_percent,
  qt_min_bet,
  qt_max_bet,
  qt_streak_2x,
  qt_streak_3x,
  qt_streak_4x,
  qt_streak_5x,
  auto_resolve_fee,
  boost_flash_price,
  boost_standard_price,
  boost_whale_price,
  broadcast_price,
  bc400_pool_percent,
  osure_enabled,
  osure_25_premium,
  osure_50_premium,
  osure_100_premium,
  social_ad_price,
  ai_generation_cost,
  welcome_bonus_percent,
  welcome_bonus_cap,
  min_liquidity,
  min_token_balance,
  min_gold_token_balance,
  min_nft_balance,
  referral_reward_amount,
  withdrawal_cooldown_minutes,
  withdrawal_multiplier,
  withdrawal_limit_enabled,
  min_withdrawal_amount,
  market_creation_fee,
  token_decimals,
  blue_max_free_markets,
  gold_max_free_markets,
  qt_enabled_assets,
  qt_enabled_timeframes,
  qt_disabled_assets,
  payout_provider,
  deposit_provider,
  token_contract_address,
  nft_contract_address,
  nft_buy_url,
  gift_fee_percent,
  prediction_min_bet,
  prediction_max_bet,
  deposit_min_amount,
  deposit_max_amount,
  push_prompt_cooldown_days,
  deposit_expiry_minutes
FROM commission_settings
LIMIT 1;
