ALTER TABLE public.commission_settings 
  ADD COLUMN IF NOT EXISTS qt_min_bet numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS qt_max_bet numeric NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS qt_streak_2x numeric NOT NULL DEFAULT 1.05,
  ADD COLUMN IF NOT EXISTS qt_streak_3x numeric NOT NULL DEFAULT 1.10,
  ADD COLUMN IF NOT EXISTS qt_streak_4x numeric NOT NULL DEFAULT 1.15,
  ADD COLUMN IF NOT EXISTS qt_streak_5x numeric NOT NULL DEFAULT 1.25,
  ADD COLUMN IF NOT EXISTS qt_enabled_assets text NOT NULL DEFAULT 'BTC,ETH,BNB,SOL,XRP,DOGE';